// Shared types for the TTS voiceover generation service.

export type TTSVoice = 'alloy' | 'echo' | 'fable' | 'onyx' | 'nova' | 'shimmer';

export interface TTSRequest {
  text: string;
  voice?: TTSVoice;
  speed?: number;
}

export interface TTSResult {
  audioUrl: string;
  durationSec: number;
}

/** Per-section timing marker for video composition sync. */
export interface SectionTiming {
  section: string;
  startSec: number;
  endSec: number;
}

/** Full UGC script object as generated by /api/generate-ugc. */
export interface UGCScript {
  hook: string;
  problem: string;
  solution: string;
  demo: string;
  socialProof: string;
  cta: string;
}

export interface ScriptToAudioResult {
  audioUrl: string;
  durationSec: number;
  timings: SectionTiming[];
}
